# ==========================================================
# Vision Transformer baseline assembled via the EPD system
# ==========================================================

exp_name: &exp_name "vit_base_epd"

model:
  encoder:
    name: ViTEncoder
    args:
      __replace__: true
      in_channels: 3
      embed_dim: 32
      patch_size: 36
      dropout: 0.1
  propagator: { name: ViTTransformer, args: { embed_dim: 32, depth: 8, num_heads: 8, mlp_ratio: 4.0, dropout: 0.1, attention_dropout: 0.0, droppath: 0.1 } }
  decoder:
    name: ViTPatchDecoder
    args:
      __replace__: true
      embed_dim: 32
      patch_size: 36
      dropout: 0.0
  head:       { name: PixelHead, args: { out_channels: 1 } }

  loss:       { name: mse }
  optimizer:  { name: adamw, args: { lr: 3.0e-4, weight_decay: 1.0e-4 } }
  scheduler:  { name: ReduceLROnPlateau, monitor: "val_total", args: { factor: 0.5, patience: 5 } }
  reg_weights: { encoder: 0.0, propagator: 0.0, decoder: 0.0, head: 0.0 }

data:
  snapshot_dir: "prep_out/mat_sparse"
  batch_size: 8
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  save_dataloaders: true

trainer:
  max_epochs: 5
  precision: "16-mixed"
  accelerator: "auto"
  devices: "auto"
  strategy: "auto"
  log_every_n_steps: 10
  val_check_interval: 0.25
  gradient_clip_val: 0.0
  accumulate_grad_batches: 1
  deterministic: true
  benchmark: false
  num_sanity_val_steps: 2
  enable_checkpointing: true
  enable_model_summary: true

logging:
  logger: "tensorboard"
  save_dir: "runs"
  name: *exp_name
  version: null

callbacks:
  early_stopping:
    enable: true
    monitor: "val_total"
    mode: "min"
    patience: 10
    min_delta: 0.0

  checkpoint:
    monitor: "val_total"
    mode: "min"
    save_top_k: 1
    save_last: true
    dirpath: null
    filename: "{epoch:03d}-{val_total:.4f}"
    load_from: null

  lr_monitor:
    enable: true
    logging_interval: "epoch"

  viz_triplets:
    enable: true
    every_n_steps: 200
    num_triplets: 4

  grad_norm:
    enable: true
    every_n_steps: 50

eval:
  enable: true
  num_eval_batches: 3
  num_plot_triplets: 6

train:
  seed: 2025
