# ==========================================================
# Vision Transformer baseline assembled via the EPD system
# ==========================================================

exp_name: &exp_name "vit_base_epd_nc"

model:
  encoder:
    name: ViTEncoder
    args: { __replace__: true, in_channels: 3, embed_dim: 64, patch_size: 40, dropout: 0.1, use_abs_pos_embed: false }
  propagator:
    name: ViTTransformer
    args:
      embed_dim: 64
      depth: 10
      num_heads: 8
      mlp_ratio: 4.0
      dropout: 0.05
      attention_dropout: 0.05
      droppath: 0.05
      use_post_smooth: true       # ← 打开“抹缝”
      post_kernel: 5
  decoder:
    name: ViTPatchDecoder
    args: { __replace__: true, embed_dim: 64, patch_size: 40, dropout: 0.1 }
  head: { name: PixelHead, args: { in_channels: 64, out_channels: 1 } }

  loss:       { name: mse }
  optimizer:  { name: adamw, args: { lr: 2.0e-3, weight_decay: 5.0e-2, betas: [0.9, 0.95] } }
  scheduler:  { name: ReduceLROnPlateau, monitor: "val_total", args: { factor: 0.5, patience: 3 } }
  reg_weights: { encoder: 0.0, propagator: 0.0, decoder: 0.0, head: 0.0 }

data:
  snapshot_dir: "prep_out/nc_full"
  batch_size: 32
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4
  drop_last: false
  save_dataloaders: true

trainer:
  max_epochs: null
  max_steps: 8000
  precision: "16-mixed"
  accelerator: "auto"
  devices: "auto"
  strategy: "auto"
  log_every_n_steps: 10
  val_check_interval: 1.0
  gradient_clip_val: 0.0
  accumulate_grad_batches: 1
  deterministic: false
  benchmark: false
  num_sanity_val_steps: 2
  enable_checkpointing: true
  enable_model_summary: true

logging:
  logger: "tensorboard"
  save_dir: "runs"
  name: *exp_name
  version: null

callbacks:
  early_stopping:
    enable: true
    monitor: "val_total"
    mode: "min"
    patience: 10
    min_delta: 0.0

  checkpoint:
    monitor: "val_total"
    mode: "min"
    save_top_k: 1
    save_last: true
    dirpath: null
    filename: "{epoch:03d}-{val_total:.4f}"
    load_from: null

  lr_monitor:
    enable: true
    logging_interval: "epoch"

  viz_triplets:
    enable: true
    every_n_steps: 200
    num_triplets: 4

  grad_norm:
    enable: true
    every_n_steps: 50

eval:
  enable: true
  num_eval_batches: 3
  num_plot_triplets: 6

train:
  seed: 2025
